language: java
before_script: cd 12f_app
script: mvn clean install
deploy:
  edge: true
  provider: cloudfoundry
  username: YOUR_USERNAME 
  api: https://api.run.pivotal.io
  organization: YOUR_ORG
  space: YOUR_SPACE
